name: C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build
      
    - name: Make
      working-directory: ${{github.workspace}}/build
      run: make
      
    - name: Make Test
      working-directory: ${{github.workspace}}/build
      run: make test
